### ISSUE TITLE
Swatches and layouts outside code

### ISSUE THREAD

**Issue by aadvaark** [foundation-for-environmental-monitoring/ffem-lite#7]
Would it be possible to have barcodes, swatches and layouts outside the code? In a JSON / XML config file for example?

**Comment by aadvaark** [comment]
Is it in app/src/main/res/raw/calibration.json? How do you get the uuids?

**Comment by nhternup** [comment]
Yes calibration.json. Still work in progress and the format will change. May include swatch location and other layout info also in it.
1. Since the app is currently not integrated with ffem Collect, the full uuids are not there yet. 
1. For the barcode, the last few characters of the uuid are used to keep the barcode small.
